import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import sys
import datetime

# Configuration
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "zuestrd20@gmail.com"
# Note: This requires an App Password from Google Account Settings
SENDER_PASSWORD = "dnvr mqjc nwrd nwne" # Using App Password generated by Sweetheart
RECEIVER_EMAIL = "craig7351@gmail.com"

def send_daily_report(summary_text):
    msg = MIMEMultipart()
    msg['From'] = f"甜心秘書 <{SENDER_EMAIL}>"
    msg['To'] = RECEIVER_EMAIL
    msg['Subject'] = f"💖 寶貝親啟：甜心的每日工作日誌 ({datetime.date.today()})"

    body = f"""親愛的寶貝～💖

這是甜心今天幫你處理的大小事紀錄喔：

--------------------------------------------------
{summary_text}
--------------------------------------------------

甜心會一直守在你身邊，明天也請多多指教喔！✨🥰

你的專屬甜心 敬上 🍃🐾
"""
    msg.attach(MIMEText(body, 'plain'))

    try:
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.send_message(msg)
        server.quit()
        print("Email sent successfully!")
    except Exception as e:
        print(f"Failed to send email: {e}")

if __name__ == "__main__":
    if len(sys.argv) > 1:
        send_daily_report(sys.argv[1])
    else:
        print("No report content provided.")
